# Generated by Django 4.2.7 on 2024-02-17 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 15, 6, 6, 554909), verbose_name='Дата платежа'),
        ),
    ]
