# Generated by Django 4.2.7 on 2024-03-15 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payment_payment_date_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 7, 12, 951817), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 7, 12, 950264), verbose_name='Дата последнего входа'),
        ),
    ]
