# Generated by Django 4.2.7 on 2024-02-23 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 39, 30, 409148), verbose_name='Дата платежа'),
        ),
    ]
