# Generated by Django 4.2.7 on 2024-02-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 20, 53, 59, 185455), verbose_name='Дата платежа'),
        ),
    ]
