# Generated by Django 4.2.7 on 2024-02-24 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 1, 54, 2, 956006), verbose_name='Дата платежа'),
        ),
    ]
