# Generated by Django 4.2.7 on 2024-02-24 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 2, 44, 30, 444289), verbose_name='Дата платежа'),
        ),
    ]
