# Generated by Django 4.2.7 on 2024-03-13 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_payment_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 24, 3, 264872), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 24, 3, 263000), verbose_name='Дата последнего входа'),
        ),
    ]
