# Generated by Django 4.2.7 on 2024-03-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='Название курса')),
                ('course_description', models.TextField(verbose_name='Описание курса')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150, verbose_name='Название курса')),
                ('lesson_description', models.TextField(verbose_name='Описание курса')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Аватар')),
                ('lesson_link', models.URLField(verbose_name='Ссылка на урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=5000, verbose_name='Цена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
