# Generated by Django 4.2.7 on 2024-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='Цена'),
        ),
    ]
